# Generated by Django 5.2.17 on 2026-09-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='weddings.wedding')),
            ],
        ),
    ]
